version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: stage_events
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: area_key
            tests:
              - not_null
          - name: stage
            tests:
              - not_null

models:
  - name: stg_stage_events
    columns:
      - name: id
        tests:
          - not_null
          - unique
